export const APP_WRITE_ID = '6860aa930023bdfbbbbe'
export const DB_ID = '6860aaf5001d82a9a883'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
